### ISSUE TITLE
Implementace platiti

### ISSUE THREAD

**Issue by Anastasionnavian** [csob/paymentgateway#532]
Dobrý den, snažím se nainstalovat platební bránu na e-shopu http://gjartshop.com/. Provedla jsem platbu v testovacím prostředí a hlásí mi chybu. Jak to můžu vyřešit? Předem děkuji

Fatal error: Uncaught Error: Call to a member function fetch_array() on bool in /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/DatabaseConnection.php:37 Stack trace: #0 /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/UniModul.php(152): MysqliConnection->sqlQuery('select * from u...') #1 /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/UniModul.php(127): UniModul->getOrderTransactionRecordFromDbPriv(NULL, '84b93c46b8043FI', NULL, NULL) #2 /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/UniCsob.php(531): UniModul->getOrderTransactionRecordFromDbUnique('84b93c46b8043FI') #3 /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/UniCsob.php(422): UniCsob->gatewayPaymentAction('status') #4 /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/wp-content/plugins/WooCommerceAdapter/Reply.php(22): UniCsob->gatewayReceiveReply('en') #5 {main} thrown in /data/web/virtuals/250206/virtual/www/domains/gjartshop.com/UniModul/DatabaseConnection.php on line 37

**Comment by dkomarek2** [comment]
Dobrý den,

z vámi uvedené chyby se mi podařilo identifikovat obchodníka s merchantID "M1MIPS8688" kdy jste poslala request označený jako objednávka "84b93c46b8043FI" odeslaný 29.9. cca 21:50.
Z logů vyplívá, že request byl v pořádku přijatý a transakce byla úspěšně zpracovaná.
Z pohledu platební brány tedy nevidím problém.

![image](https://user-images.githubusercontent.com/67467762/95322832-6a39e980-089d-11eb-8b5a-dc17755dab61.png)

Z logu jsem ještě pochopil, že zřejmě využíváte "WooCommerce" plugin, který ovšem není již bankou podporovaný a nemohu vám tedy s jeho funkčností nijak pomoci.

Pokud by jste použila naše standartní eAPI bez použití tohoto pluginu, pak vám rád pomůžu.
Podrobnější informace naleznete v místní Wiki sekci.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by Anastasionnavian** [comment]
Dobrý den,

před tím než jsme kupovali plugin CSOB platební brána od Platiti.cz,
konzultovala jsem to s vaším kolegou a bylo mi řečeno, že platební brána je
kompatibilní s WooCommerce. Chápu to správně, že teď buď nemůžeme
používat platební bránu v plném rozsahu, nebo musíme předělat e-shop bez
použití WooCommerce?

S pozdravem,
Anastasiia Najmušinová

st 7. 10. 2020 v 13:06 odesílatel dkomarek2 <notifications@github.com>
napsal:

**Comment by janbrasna** [comment]
@Anastasionnavian Spise je potreba se obratit na Platiti.cz jako tvurce toho kodu — tyto chyby z jejich modulu (ala `UniModul/UniModul.php` ci `UniModul/UniCsob.php`) vypadaji na nejake problemy s vyhodnocenim na jejich strane, pripadne na PHP/SQL u vas; nic z techto chyb se netyka samotne platby, ale az dalsich operaci vaseho systemu.

**Comment by dkomarek2** [comment]
Dobrý den,

jak uvedl @janbrasna , problém bude na straně pluginu, a s tím vám pomůže jeho tvůrce a nikoli my.
Za nás byla komunikace s platební bránou v pořádku. Pokud by byl problém s touto komunikací, pak vám rádi pomůžeme s odladěním.
Myslel jsem to tedy tak, že s funkčností pluginu vám nepomůžu, ta část komunikace o kterou se stará naše firma byla v pořádku.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by mertuarez** [comment]
pozri si sql subor asi ti chyba tabulka v db.
